### ISSUE TITLE
Can we use this to install package managers too ?

### ISSUE THREAD

**Issue by jcampbell05** [bfontaine/up#1]
Can we use this to install package managers too ?

**Comment by bfontaine** [comment]
Nope, it’s mostly an aliases manager; that’s all. But feel free to grab the script and change it to do what you want :smiley:

**Comment by bfontaine** [comment]
We could also make a package manager for package managers. Some sort of package manager manager :smile:

**Comment by jcampbell05** [comment]
Yo Dawg....
